### ISSUE TITLE
Notebook crash

### ISSUE THREAD

**Issue by Korijn** [flexxui/flexx#187] opened 2016-08-22 13:29 UTC
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-8-4ee138864a30> in <module>()
     11 import os
     12 
---> 13 app.init_notebook()
     14 
     15 from IPython.core.display import display, HTML

C:\Users\User\Miniconda3\envs\myapp\lib\site-packages\flexx\app\funcs.py in init_notebook()
    243 
    244     # Get session or create new, check if we already initialized notebook
--> 245     session = manager.get_default_session()
    246     if session is None:
    247         session = manager.create_default_session()

C:\Users\User\Miniconda3\envs\myapp\lib\site-packages\flexx\app\session.py in get_default_session(self)
     77             _, pending, connected = x
     78             proxies = pending + connected
---> 79             return proxies[-1]
     80 
     81     def _clear_old_pending_sessions(self):

IndexError: list index out of range
```

**Comment by almarklein** [comment] 2016-08-29 22:42
How should I try to reproduce this?

**Comment by almarklein** [comment] 2018-02-06 13:04
Closing since so much has changed in that code that it now works (or breaks differently). Please re-open if it persists :)

**Closed by almarklein** 2018-02-06 13:04 UTC
Labels: tag: app, type: bug
