### ISSUE TITLE
ui.ImageWidget: image scaling changes when resizing window

### ISSUE THREAD

**Issue by eudoxos** [flexxui/flexx#215] opened 2016-09-16 08:23 UTC
The following MWE shows image being scaled in funny ways; the inlined image is 1600x981 blue frame (and otherwise transparent); it is initially shown as tiny image in middle left, then resizes as the window is resized, but sometimes is much smaller than the window without any obvious constraint, sometimes fills the available space (without changing aspect ratio, which is expected).  A way to specify that the image should always occupy 100% width or something similar should be provided. I did not find a way to do it with style args:

```
blueframe='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABkAAAAPVAQMAAAAEUbSzAAAABlBMVEUAAAAAAP+IZVZCAAAAAXRSTlMAQObYZgAAAAFiS0dEAIgFHUgAAAAJcEhZcwAAD2EAAA9hAag/p2kAAAAHdElNRQfgCRALAA31fReQAAADI0lEQVR42u3PAREAIAgEMJrbXDxaeM/WYNUhSkRERERERERERGRTpAJM5CZEjoiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIiIyIeRToj0RDKIiIiIiIiIiIiI7Ik8j2dJnAX2fgkAAAAASUVORK5CYII='

from flexx import app, ui

class ImgHt(ui.Widget):
    def init(self):
        with ui.VBox():
            ui.ImageWidget(source=blueframe)

app.launch(ImgHt)
app.start()
```

**Comment by almarklein** [comment] 2016-09-16 11:53
Thanks for using Flexx and reporting all these issues, its very useful! I am going to try and trick you into becoming a contributor ;) I think this should be relatively easy to fix by changing code [here](https://github.com/zoofIO/flexx/blob/master/flexx/ui/widgets/_media.py#L78-L95) by hooking the JS `load` event to the  `__resize_image` method (via `addEventListener`), similar to [here](https://github.com/zoofIO/flexx/blob/master/flexx/ui/widgets/_button.py#L114).

**Comment by eudoxos** [comment] 2016-09-16 12:02
I was looking at that code already, but the I realized there was a layouting problem, so the example I added in the the edited issue does not change source at all.

It might also be my lack of understanding how PhosphorJS + Flex + CSS work all together. E.g. in Qt, a widget will (mostly) extend to the size of its parent widget (unless there is a layout applied), so e.g. putting ImageWidget inside a HBox would make the image span across the width, but perhaps I am applying desktop paradigms/habits too much. A way of saying: extend horizontally/vertically as much as possible would be useful.

For ImageWidget, what is the "good" way to access the HTML element it wraps? Is it ImageWidget.node? I tried setting its style, but I assume PhosphorJS does that on resize as well, so nothing was changing.

**Comment by eudoxos** [comment] 2016-10-13 15:36
Please feel free to conclude this is a problem in Phosphor, it is really the layouting which does funny things when resizing.

**Comment by almarklein** [comment] 2016-10-13 19:18
Thanks, but I think this is an issue of Flexx, since Phosphor has little to do with this widget in particular. Will have a look for sure, but it's not my top priority right now :)  I marked it for 0.5 though, so I should get to it soonish.

**Comment by almarklein** [comment] 2018-03-21 21:51
I cannot reproduce this problem with the current version of Flexx. I'm pretty sure that I touched this code during the recent big refactoring. I'm therefore closing this. Please reopen if you still see the issue.

**Closed by almarklein** 2018-03-21 21:51 UTC
Labels: tag: ui, type: bug

**Comment by jakspacek** [comment] 2020-01-27 17:42
Hi, I was having a similar problematic behaviour with images in imagewidgets contained within a VBox not being given their proper minimum space, and resizing the window would make them gradually move up to the proper size. This behaviour persisted regardless of flex=x values (incl. flex=0 on the imagewidget) on each element. I fixed it by giving my ImageWidget a css 'minHeight' property, but notably a css 'minWidth' property did not work.

I am using the most recent version of Flexx and was testing in the latest Firefox.

Cheers!
