### ISSUE TITLE
GroupWidget rendering issue

### ISSUE THREAD

**Issue by matkuki** [flexxui/flexx#593] opened 2019-10-11 20:39 UTC
Hi, finally found the problem.
This code works without problems (just renders one `Groupwidget` with one `ComboBox`):
```python
from flexx import flx, ui, event, config

class GBX(flx.GroupWidget):
    CSS = f"""
        .flx-GBX legend {{
            font-family: Helvetica;
            font-size: 16px;
            font-weight: bold;
        }}
    """

class Test(flx.Widget):
    def init(self):
        with flx.VBox(padding=0, spacing=10):
            with flx.HBox(padding=0, spacing=0):
                    with GBX(title="SOME LONG GROUPBOX TITLE", flex=1):
                        with flx.VBox():
                            flx.ComboBox(
                                editable=False,
                                options=["ONE", "TWO", "THREE"],
                                selected_index=0,
                            )
            flx.Widget(flex=1)
test_app = flx.App(Test, title="TEST")
test_app.serve('')
flx.start()
```
![image](https://user-images.githubusercontent.com/10289651/66683449-bd239580-ec77-11e9-9140-f41519e914c6.png)

But change the line `class Test(flx.Widget):` to `class Test(flx.PyWidget):`, and about 4 out of 10 times the `GroupWidget` layout is messed up like so:
![image](https://user-images.githubusercontent.com/10289651/66683488-db899100-ec77-11e9-9fd6-9b4ad749a72b.png)

P.S.:
Simplified the example code.

**Comment by jrversteegh** [comment] 2019-10-13 08:45
I can reproduce this. Could you try to make your example minimal? I noticed you can remove a lot without losing this behaviour..

**Comment by jrversteegh** [comment] 2019-10-13 10:04
It seems like the order of the inline css is different for PyWidget than for Widget.

For the simplest example the order with Widget is:
 * _widget.css
 * _layout.css
 * _hv.css
 * _dropdown.css
 * _group.css

While for PyWidget:
 * _widget.css
 * _group.css
 * _layout.css
 * _hv.css
 * _dropdown.css

Manually adding a copy of the contents of _group.css at the end fixes the issue. Even if you only add the `.flx-GroupWidget > .flx-Layout` rule. Does this rule only work properly after styling of .flx-Layout? This is beyond my CSS knowledge. It seems like a good idea though that css is loaded in the same order regardless of Widget or PyWidget to avoid these kind of issues @almarklein

**Comment by almarklein** [comment] 2019-10-14 09:41
I can indeed reproduce this. Thanks @jrversteegh to confine the issue to the order that Flexx defines the assets. I looked into that part, and the cause seems to be in the difference between how a PyComponent and JsComponent are initialized. It does not seem to be a problem specific to `PyWidget`.

When a `JsComponent` (e.g. `Widget), gets instantiated in Python, it registers itself with the session (via `_register_component`). The session will resolve its dependencies (modules), as derived from the source code of that class, and will push the CSS and JS sources to the browser the in the correct order, the module that defines the instantiated `JsComponent` last (e.g. `__main__`).

When a `PyComponent` gets instantiated, the same thing happens, but in this case the source is not used to derive depenendencies - it's a Py-Component, so it does not undergo the magic transpilation step. At some point (usually during the `init()`, it will instantiate a `JsComponent`, and the above paragraph applies.

In the example at the top post, this means that the `__main__` module gets loaded first, but since it depends on `flx.GroupWidget` (via the `GBX` class), the `flexx.ui.widgets._group.css` gets loaded "too soon" too.

I'm not sure how feasible a solution would be to ensure consistent loading. But a way to make things work is to put the sources of your custom non-py widgets (e.g. `GBX`) in a separate module.

**Comment by jrversteegh** [comment] 2019-10-14 11:37
> put the sources of your custom non-py widgets (e.g. GBX) in a separate module

That may not be sufficient. Without custom js widgets, you can still get this behaviour e.g.:

```
from flexx import flx

class Test(flx.PyWidget):
    def init(self):
        with flx.GroupWidget(title="SOME LONG GROUPBOX TITLE"):
            with flx.VBox():
                flx.ComboBox(options=["ONE", "TWO", "THREE"], selected_index=0)

entry = flx.App(Test, title='')
entry.serve('')
flx.start()
```

Since GroupWidget comes first, its CSS will be loaded first? If the order of the css is indeed important then it seems to me some kind of dependency tracking is required... Or GroupWidget should not be allowed to have a "non layout" parent or something, so it can never occur in source before a layout. 

Regarding the second: seems I've been bitten by parenting issues before ( #501 ). I Think beginners would be helped by errors or warnings in case of "bad parenting" ;)

**Comment by almarklein** [comment] 2019-10-14 19:15
> Since GroupWidget comes first, its CSS will be loaded first

oh ... I think you might be right. In that case, a better solution would be to update the CSS for the groupwidget so it won't be overrriden.

**Comment by jrversteegh** [comment] 2019-10-14 20:09
`.flx-box.flx-vertical` in _hv.css appears to be its competitor.

Like so? #595

**Comment by almarklein** [comment] 2019-10-15 08:53
Yes, I confirmed that it worked, and merged your PR :)

**Closed** 2019-10-15 08:53 UTC
