### ISSUE TITLE
i got problem before i  packet .py to .exe

### ISSUE THREAD

**Issue by ub3132003** [flexxui/flexx#472] opened 2018-06-26 07:19 UTC
dose anyone packet this module to .exe . it's always cue that error

**Comment by almarklein** [comment] 2018-06-27 07:30
Sorry, but your message does not have any information that helps target was is going wrong. In any way, freezing is not yet officially supported (see #260 and #433).

**Comment by ub3132003** [comment] 2018-06-29 09:52
thanks. that's very helpful supported.  I guess the errors from packet relationship. I may con't use cx_freez or pyinstall in rigth way.

**Comment by almarklein** [comment] 2018-09-05 13:11
Duplicate of #260

**Closed by almarklein** 2018-09-05 13:11 UTC

**Comment by almarklein** [comment] 2018-09-13 08:07
Not yet, but issue #260 described the same issue; we'll be using that to track progress, and I closed this as being a duplicate.
