### ISSUE TITLE
Bokeh plot does not show up in VBox (and possibly other containers)

### ISSUE THREAD

**Issue by eudoxos** [flexxui/flexx#209] opened 2016-09-14 10:21 UTC
Using this simple script with 2 plots, the first one appears normally, but the other one inside a tabbed VBox does not; if the second one is moved out of the VBox, it appears as second tab normally. This is an adapted MWE based on with_bokeh.py:

```
import numpy as np
from bokeh.plotting import figure
from flexx import app, ui, event
from flexx.pyscript import window

N = 1000
x = np.random.normal(0, np.pi, N)
y = np.sin(x)+np.random.normal(0, 0.2, N)
p1,p2=figure(),figure()
p1.scatter(x,y)
p2.scatter(x,y)

class Example(ui.Widget):
    def init(self):
        with ui.TabPanel():
            self.plot1=ui.BokehWidget(plot=p1, title='Scatter 1')
            with ui.VBox(title='Container'):
               self.plot2=ui.BokehWidget(plot=p2, title='Scatter 2')

if __name__ == '__main__':
    m=app.launch(Example)
    app.start()
```

**Comment by almarklein** [comment] 2016-09-14 12:42
Reproduced. Thanks!

**Comment by almarklein** [comment] 2018-02-06 13:09
The example now looks likt this, and the issue is still there:
```py

import numpy as np
from bokeh.plotting import figure
from flexx import app, ui, event
from flexx.pyscript import window

N = 1000
x = np.random.normal(0, np.pi, N)
y = np.sin(x)+np.random.normal(0, 0.2, N)
p1,p2=figure(),figure()
p1.scatter(x,y)
p2.scatter(x,y)

class Example(app.PyComponent):
    def init(self):
        with ui.TabLayout():
            self.plot1 = ui.BokehWidget.from_plot(p1)
            with ui.VBox(title='Container'):
                self.plot2 = ui.BokehWidget.from_plot(p2)
        
        self.plot1.set_title('Scatter 1')
        self.plot2.set_title('Scatter 2')

m=app.launch(Example)
app.start()
```

**Comment by almarklein** [comment] 2018-04-19 22:12
With #465 (to be merged), the Bokeh plot also has a minimum size. A HBox will still not fill the widget up if it has a `flex=0` though. So either use `VFix`, or `self.plot2 = ui.BokehWidget.from_plot(p2, flex=1)`.

**Closed** 2018-04-19 23:37 UTC
Labels: tag: ui, type: bug
