### ISSUE TITLE
Memory leak in PyWidget

### ISSUE THREAD

**Issue by matkuki** [flexxui/flexx#721] opened 2022-02-22 11:32 UTC
Looks like the PyWidget never gets garbage-collected. Causing all its attributes to stick around too. When these contain e.g. large datasets, this can cause severe memory leaks.

This needs some research to see what is holding a ref, and if we can solve this using e.g. a weakref. See a self-contained test-example further down.

----
*original post*

Hi @almarklein,

I have a `flx.PyWidget` that has `flx.Widget` that wraps a javascript widget as a member:
```python
class MyWrappedWidget(flx.Widget):
  ...
  def dispose(self):
    # clean up code
    print("clean-up-completed")

  @flx.action
  def manual_dispose(self):
    # clean up code
    print("manual-clean-up-completed")

class MyPyWidget(flx.PyWidget):
  def init(self):
    with flx.VFix(flex=1) as self.frame:
      self.mywidget = MyWrappedWidget() # the wrapped widget defined above

  def dispose(self):
    # self.mywidget.dispose()
    self.mywidget.manual_dispose()
    print("MyPyWidget-clean-up")
```
Now when the `flx.PyWidget` is disposed, the `manual_dispose` call **seems to be made, but doesn't execute**, the `print` is never made to the command line. 
I also tried calling the `flx.Widget`'s `dispose` method directly, but it's also doesn't execute.
The wrapped `flx.Widget` (MyWrappedWidget) can be quite large (100's of MBs), so when old ones should be deleted and new ones created, the memory just stacks up, it doesn't get released. That's how it seems to me, don't hold me to this, I may be wrong.

Is there a way to force the child `flx.Widget` to get disposed?

**Comment by matkuki** [comment] 2022-02-23 08:21
More info:
I'm testing this by adding the `MyPyWidget` to a parent `flx.PinboardLayout` widget, displaying it in a browser, then closing the tab.
`MyPyWidget`'s `dispose` method is called correctly, but `MyWrappedWidget`'s is not.

**Comment by matkuki** [comment] 2022-03-01 21:55
Just did some more testing and it seems that the problem is with the `Session` or `App` closing too early, as if all the signals that need to be called to `dispose` the remaining objects of a `Session`/`App`just don't appear to be called.

**Comment by matkuki** [comment] 2022-03-08 11:08
Hey @almarklein 
Can you please direct me to the part of the code where memory issues could be located?
Just a rough idea of what I should look for, as I am currently disoriented with the code.

Thanks

**Comment by almarklein** [comment] 2022-03-14 09:24
Hey @matkuki, sorry for the late reply. 

Could you tell some more about the use-case?

I played a bit with the code and what I see is that:
* If you call the `MyPyWidget.dispose()`, then all prints gets printed.
* You can also call `self.mywidget.dispose()` from inside `MyPyWidget.dispose`.
* If `MyPyWidget` gets disposed because the app closes down, the prints at the JS side are *not* printed.

The latter can be explained because the actions are scheduled (e.g. the call to `manual_dispose`), but the event loop is no longer active, so they never get communicated to JS. But I suppose this is ok, because when the app closes down, this is either because the user closed it, or the server closes down, and this will close the connection and invalidate/close the app too.

**Comment by matkuki** [comment] 2022-03-14 10:17
Hi @almarklein ,
Ah, thanks for the explanation. So the printing is not necessary, got it. Then I don't know where the problem is.
The above example I gave is a bit simplified, the actual `MyPyWidget` has a wrapped widget (tabulator table) and a data checker object (pure python) as an attribute: `MyPyWidget.table` and `MyPyWidget.data_checker`. `MyPyWidget.table` is just a straight wrapper for a Tabulator, but the data checker uses a self calling `asyncio.get_event_loop().call_later` routine to check if some data on disk changes (the data can be large, for example a `100 columns * 300 rows` table in which every cell is a string).
When I start the application the memory usage is minimal at about `50MB`, then a few tables are opened and the memory usage goes to `260MB`. Then when the client closes the page the memory usage drops to about 150MB. Then when the client connects again to the application and opens the same tables the memory goes to `390MB` and when closed again the memory only drops to about `250MB`, and so on.
One observation is that 1-in-10 times, the memory does get cleaned up: the memory starts at `50MB`, goes to `260MB`, then drops to about `60MB` when a client disconnects (and repeat connections to the application only raise memory usage by about `10 - 20MB` of memory). Ok, this is a small memory leak, but this one is very managable.
In the past you suggested that I restart the application once a day to avoid this and that was a great fix, but then this happened:
I have a small parallel process that restarts the application at a certain time of day. But the application had a lot of user connections/disconnections on one specific day and the memory usage ballooned to over `4.5GB`. As this is running on a virtual machine, the OS did something that made the parallel process die (there probably was a traceback, but I don't have it), so the application never restarted.
You also advised some time ago that a docker image that gets restarted when memory usage gets too high, but I cannot kill the application as somebody is still connected to the application, the users would not like that.
This is on `Windows 10 x64`, `Python3.7`, `flexx` installed through `pip`, memory is observed in Windows task manager.

If there is any way of locating where the offending memory usage is located in the application or maybe a design pattern I could try applying to `MyPyWidget` to get rid of this memory leak?

Thanks

**Comment by almarklein** [comment] 2022-03-14 14:02
So in your use-case the problem is that it looks like some Python objects are not released. Not JS related IIUC.

I imagine that you have something in the `MyPyWidget.dispose` to remove the table. You could try adding something like this to make sure that Python actually cleans up its memory at that moment: `import gc; gc.collect()`.

**Comment by matkuki** [comment] 2022-03-19 12:43
Hey @almarklein 

I have already tried deleting big data lists (of strings) explicitly and putting `gc.collect()` after all those instances, but no change except that there is a bigger delay when the this code is called.

After doing some more tinkering around, I think the offending objects are all  that inherit from `PyWidget`.
Every attribute I put on a `PyWidget` (for example `MyPyWidget.big_list` or `MyPyWidget.big_object`) never seems to get cleaned up, even when deleting explicitly (e.g.: del `MyPyWidget.big_list`; `MyPyWidget.big_list` = None; gc.collect()) inside `MyPyWidget.dispose()` and making sure it gets called by inserting a print statement inside `MyPyWidget.dispose`.

**Comment by matkuki** [comment] 2022-03-21 14:10
Hey @almarklein 

**Confirmation**:
I added the manual deletions to my server application that users log in and out of it during the entire day, and the finding is: memory usage previously was between 3500MB and 4200MB, and now **1900-2000MB**! And I did this only on one `PyWidget`, the one with the most number of attributes. If I did it for all of them (about 15), I could probably get it down more.

Does this maybe give any hints of where the problem is?

**Comment by almarklein** [comment] 2022-03-21 21:52
Yes, it's suspicious that the `PyWidget.__del__` never gets called. This might suggest that there are lingering refs to it. Would be good to first confirm this is due to the internals of Flexx and not the specific application. Maybe a minimal demo app to reproduce the issue or something.

**Comment by matkuki** [comment] 2022-03-22 20:57
@almarklein
No problem, here you go. Just keep opening and closing `http://localhost:49190/demo/` in a tab and the memory should jump by about 500MB each time, and `__del__` never gets called (it only gets called for all widget instances when you `CTRL+C` the app).
**Note that this is on Windows**, haven't tested on `Linux`.
```
from flexx import flx

class Demo(flx.PyWidget):
    
    def __del__(self):
        print("Demo-__del__")
        super().__del__()
    
    def dispose(self):
        print("Demo-dispose")
        super().dispose()
    
    def init(self):
        super().init()
        
        self.big_list_0 = []
        for i in range(100_000):
            new_item = {}
            for j in range(100):
                new_item[j] = "Some test string things"
            self.big_list_0.append(new_item)
        print("big_list_0 created")
        
        with flx.PinboardLayout(flex=1) as self.frame:
            self.label = flx.Label(text="Test", flex=0, style="color: black; font-size: 30pt; width: 200px; height: 200px;")
        


if __name__ == '__main__':
    a = flx.App(Demo, title='Flexx demo')
    a.serve("demo")
    flx.start()
```

**Comment by almarklein** [comment] 2022-03-22 22:08
Thanks! I'll try to have a look soon. I also updated the title and the top post to describe the issue as we now understand it.

**Comment by matkuki** [comment] 2022-04-08 21:52
Any progress?

**Comment by almarklein** [comment] 2022-04-11 08:59
I had a go at the code above, and can reproduce the problem (on MacOS). However, if I continue reloading the page, at *some* point, the `__del__` method of all previous widgets gets called. So it looks like the `PyWidget` does not have lingering refs, but the GC simply decides to clean up rather late. I'm not sure why, but even though I see the `__del__` being called, the memory is not reduced, and keeps growing if I refresh some more, as if the big lists are *not* removed, which is very odd ...

Anyway, if I add `gc.collect()` in the `init()`, the `__del__` gets called on every new connection, resulting in a stable memory usage. So maybe this should be the solution: add `gc.collect()` in the `init()` of the widget that represents the application, so that on each new connection, you trigger the GC.

Another solution could be that Flexx invokes the GC when as session is closed. Should probably be done a bit smart, e.g. rate-limit that to avoid overhead in servers with a lot of coming and going traffic.

**Comment by matkuki** [comment] 2022-04-11 09:21
I have just tried adding `gc.collect()` at the top of `init()`, and indeed the `__del__` gets called after the second connection, but memory usage is still going up as before, no changes. After six reloads the memory is at about 3GB, which is huge. Note that this is on Windows 10.

**Comment by almarklein** [comment] 2022-04-11 09:37
I think this may be the cause:

https://github.com/flexxui/flexx/blob/de8aa263b4e5347868fe5c9da5bfc35a4791274d/flexx/event/_component.py#L348-L351

**Comment by almarklein** [comment] 2022-04-12 09:10
I meant that it looked suspicious, because what happens there is a bit weird (it actually prevents the object being collected by creating a new reference to it). But in retrospect I don't think it should matter for this case; when the session closes, it first calls `dispose` on the root component, and then releases the reference to it, so that `__del__` should be a no-op.

I just tried on Windows, and I can see that the memory does not increase if I use the extra `gc.collect()` call. However, if I refresh in quick succession, it *does* increase. What happens then, is that new connections are made, but since the old ones take a second or so to disconnect, multiple sessions are active at a time. After a minute or so, if I then refresh a few times (at a gentle pace), I see the memory return to normal again (looks like it need multipe calls to `gc.collect()` to do a complete collection.

Another thing I noticed, is that if I refresh gently, I see the dispose being called. But if I refresh quickly, I don't. It looks like the session exists so short, that the application is created, but not registered yet with the session, so it is not cleaned up correctly ...

**Comment by almarklein** [comment] 2022-04-12 09:53
mmm, interesting that it behaves differently from what I see. 

Could you try changing that "suspicious code" that I mentioned above to:
```py
    def __del__(self): 
        if not self._disposed: 
           self._dispose()
```

and see if that helps? It's a bit of a long shot, but I don't know what else to try right now 😕

**Comment by matkuki** [comment] 2022-04-12 10:03
SUCCESS!!!!!!! THE ABOVE CHANGE WORKS:

https://user-images.githubusercontent.com/10289651/162935402-300c7962-bdd4-4c3a-92a3-4746abface17.mp4

**Comment by matkuki** [comment] 2022-04-12 10:16
Just this small change also fixes my problem with the wrapped `Tabulator` table javascript widget, without adding the `gc.collect()` into my `init` methods 👍👍👍👍

**Comment by almarklein** [comment] 2022-04-12 15:00
It's funny, because that change alone, does not fix things for me. So let's do both. #725

**Comment by matkuki** [comment] 2022-04-12 15:05
Very good 👍

**Closed** 2022-04-12 19:08 UTC

**Comment by almarklein** [comment] 2022-04-12 19:14
Also made a new release. Thanks @matkuki for your help in fixing this!

**Comment by matkuki** [comment] 2022-04-12 19:17
Thank you @almarklein for finding the problem and the fix 🎉🎉🎉
